### PR TITLE
Drafting flare-for with static key-value semantics

### PR DESCRIPTION
**Pull request by phorward**
This is a draft for the flare-for-Feature.

This already runs well:

```python
from flare import *

html5.Body().appendChild("""
<select flare-for="items">
    <option value="{{key}}">{{value}}</option>
</select>
""", items={"glider": "Segelflugzeug", "motorglider": "Motorsegler", "microlight": "Ultraleicht"}
)

html5.Body().appendChild("""
<select flare-for="items">
    <option value="{{value}}">{{value}}</option>
</select>
""", items=["Segelflugzeug", "Motorsegler", "Ultraleicht"]
)

html5.Body().appendChild("""
<select flare-for="items">
    <option value="{{value}}">{{value}}</option>
</select>
""", items=1337
)
```

### CODE REVIEW

**Comment by phorward** [comment]
#9

**Comment by sveneberth** [comment]
Great, but i would like to have a more flexible unpacking. Especially in edit-forms _value_ might be already used for currently stored value in the dataset, and will be shadowed.
And unpacking a list of tuples would be nice as well:
```python
html5.Body().appendChild("""
<select flare-for="(name, price, amount) in items">
    <option value="{{value}}">{{value}}</option>
</select>
""", items=[("EAN001", 150, 1), ("EAN071", 20.59, 3)]
)
```

**Comment by phorward** [comment]
> And unpacking a list of tuples would be nice as well:
> 
> ```python
> html5.Body().appendChild("""
> <select flare-for="(name, price, amount) in items">
>     <option value="{{value}}">{{value}}</option>
> </select>
> """, items=[("EAN001", 150, 1), ("EAN071", 20.59, 3)]
> )
> ```

Sure, but this can be achieved as well like this (you didn't used your tuples, now I did for you).
```python
html5.Body().appendChild("""
<select flare-for="items">
    <option value="{{value[0]}}">{{value[1]}} x {{value[0]}} * {{value[2]}}</option>
</select>
""", items=[("EAN001", 150, 1), ("EAN071", 20.59, 3)]
)```
When you want unpacking, please tell me more about the syntax and what could be possible. Because there's always this "in"-operator, which is obsolete because it's always there. Maybe I'm wrong with this.

**Comment by phorward** [comment]
I'm thinking also about if-conditions like in list-comprehensions here... so that things can be filtered out, e.g. `flare-for="aircraft in aircrafts if aircraft["seat"] > 1`

**Pull request merged**
